import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import logo from "../../public/logo.png";
import mark from "../../public/mark.png";
import name from "../../public/name.png";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>gLabs Contacto</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center">
      <h1 className="text-main text-3xl mt-10">Formulario de Contacto</h1>
        <form
          action=""
          className="bg-main rounded-3xl text-secondary sm:w-[80%] md:w-[30%] p-5 pb-7 md:m-10 mt-5 sm:mb-10 md:mb-52 flex flex-col gap-4"
        >
          <div className="flex flex-col">
            <label htmlFor="">Nombre</label>
            <input
              type="text"
              className="bg-secondary text-white rounded-md px-2"
              required
            />
          </div>
          <div className="flex flex-col">
            <label htmlFor="">Apellido</label>
            <input
              type="text"
              className="bg-secondary text-white rounded-md px-2"
              required
            />
          </div>
          <div className="flex flex-col">
            <label htmlFor="">Email</label>
            <input
              type="email"
              className="bg-secondary text-white rounded-md px-2"
              required
            />
          </div>
          <div className="flex flex-col">
            <label htmlFor="">Numero de Telefono</label>
            <input
              type="number"
              className="bg-secondary text-white rounded-md px-2"
              required
            />
          </div>
          <div className="flex flex-col">
            <label htmlFor="">Empresa</label>
            <input
              type="text"
              className="bg-secondary text-white rounded-md px-2"
            />
          </div>
          <div className="flex flex-col">
            <label htmlFor="">Mensaje</label>
            <textarea
              name=""
              id=""
              className="bg-secondary text-white rounded-md px-2"
              required
            >
              Escribe aqui...
            </textarea>
          </div>
          <div className="flex justify-center ">
            <input type="submit" className="bg-white rounded-xl p-3 px-5" />
          </div>
        </form>
      </main>
    </>
  );
}
