import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import logo from "../../public/logo.png";
import mark from "../../public/mark.png";
import name from "../../public/name.png";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>gLabs Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="./favicon.ico" />
      </Head>
      <main>
        <div className="flex flex-row my-48 ml-40">
          <div className="flex flex-col gap-4 text-7xl">
            <p className="text-white">El futuro de las</p>
            <p className="text-white">
              <span className="text-main">
                <i>Aplicaciones</i>
              </span>{" "}
              de
            </p>
            <p className="text-white">
              <span className="text-main">
                <i>Gestion</i>
              </span>{" "}
              de
            </p>
            <p className="text-main">
              <i>Proyectos</i>
            </p>
            <p className="text-white">ha legado</p>
          </div>
          <div className="ml-28 -mt-6">
            <Image src={mark} alt="mark" height={470} />
          </div>
        </div>
      </main>
    </>
  );
}
