import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import logo from "../../public/logo.png";
import mark from "../../public/mark.png";
import name from "../../public/name.png";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>gLabs Sobre Nosotros</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-row justify-center gap-10">
        <div className="h-[650px] w-[200px] -ml-32 border border-main border-t-0 rounded-t-none rounded-full text-center text-white sm:hidden md:inline-block">
          <div className="my-14 px-3">
            <p className="text-main text-3xl mb-3">600</p>
            <p> Proyectos Intregardores Almacenados</p>
          </div>
          <hr className="border-main" />
          <div className="my-14 px-3">
            <p className="text-main text-3xl mb-3">25</p>
            <p>Clientes satisfechos</p>
          </div>
          <hr className="border-main" />
          <div className="my-14 px-3">
            <p className="text-main text-3xl mb-3">300</p>
            <p>GBs almacenados de manera segura</p>
          </div>
        </div>
        <div className="md:grid md:grid-cols-2 md:w-[60%] md:pl-10 md:py-10 md:gap-16 text-white p-10">
          <div className="sm:hidden md:inline-block">
            <Image src={mark} alt={"mark"} height={200} />
          </div>
          <div className="">
            <h1 className="text-2xl text-main pb-2">El problema</h1>
            <p>
              El problema que gLabs intenta solucionar es la necesidad de las
              empresas de adaptarse y aprovechar las oportunidades que ofrece la
              era digital. Muchas organizaciones se enfrentan a desafíos como la
              automatización de procesos, la gestión y análisis eficiente de
              grandes volúmenes de datos, la integración de sistemas heredados,
              la seguridad de la información y la optimización de la experiencia
              del cliente, entre otros. Estos desafíos pueden obstaculizar el
              crecimiento y la eficiencia de las empresas, así como su capacidad
              para mantenerse competitivas en un entorno empresarial en
              constante evolución.
            </p>
          </div>
          <div className="md:hidden mb-10">
            <Image src={mark} alt={"mark"} height={200} />
          </div>
          <div className="">
            <h1 className="text-2xl text-main pb-2">Como lo solucionamos</h1>
            <p>
              gLabs soluciona los problemas empresariales utilizando un enfoque
              personalizado, tecnologías avanzadas y una comprensión profunda de
              las necesidades y objetivos de nuestros clientes. Nuestro objetivo
              es brindar soluciones efectivas que impulsen el crecimiento, la
              eficiencia y la competitividad de las empresas en la era digital.
            </p>
          </div>
          <div className="sm:hidden md:inline-block">
            <Image src={mark} alt={"mark"} height={200} />
          </div>
          <div className="mb-10">
            <Image src={mark} alt={"mark"} height={200} />
          </div>
          <div className="">
            <h1 className="text-2xl text-main pb-2">El Objetivo</h1>
            <p>
              El objetivo de gLabs es desarrollar soluciones innovadoras y
              tecnológicas que impulsen el crecimiento y el éxito de nuestros
              clientes. Nuestro enfoque se centra en brindar servicios de
              consultoría, desarrollo de software y soluciones personalizadas
              que ayuden a las empresas a optimizar sus operaciones, mejorar su
              eficiencia y obtener una ventaja competitiva en el mercado.
              Buscamos ser líderes en la creación de soluciones disruptivas y
              vanguardistas que aborden los desafíos empresariales actuales y
              futuros, utilizando tecnologías avanzadas como inteligencia
              artificial, análisis de datos, Internet de las cosas (IoT) y
              blockchain. Nuestro objetivo final es ser un socio confiable y de
              confianza para nuestros clientes, brindándoles soluciones que
              impulsen su crecimiento y éxito en la era digital.
            </p>
          </div>
        </div>
      </main>
    </>
  );
}
