import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import logo from "../../public/logo.png";
import mark from "../../public/mark.png";
import name from "../../public/name.png";


const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>gLabs Tutorial</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen text-white">
        <h1 className="text-center">Tutorial</h1>
        <Image src={logo} alt={"logo"} height={100} />
      </main>
    </>
  );
}
